### ISSUE TITLE
awesome-wow-rust

### ISSUE THREAD

**Issue by arlyon** [gtker/wow_srp#3]
Hi!

I have been working on azerust on and off (mostly off) and decided it would be great to have a common hub to share resources for people working on wow-related projects in rust. I have added a list here: https://github.com/arlyon/awesome-wow-rust. Please consider opening a PR with any useful crates.

**Comment by gtker** [comment]
Hey,

Sorry for being late to respond. I actually saw your message within hours of you posting it, but I never got around to replying.

Looks like a very cool initiative. I've also got [wow_vanilla_dbc](https://github.com/gtker/wow_vanilla_dbc), although I have plans for adding TBC and Wrath support as well through [WoWDbDefs](https://github.com/wowdev/WoWDBDefs), so I might end up renaming the repo and deprecating the [wow_vanilla_dbc crate I published](https://crates.io/crates/wow_vanilla_dbc).

I am also (locally) working on a crate for general business logic for WoW servers that really don't need to be duplicated, like default stats for characters, teleport locations, valid class/race combos, etc. although it will probably be slightly delayed because I'm working on adding Wrath support to [wow_messages](https://github.com/gtker/wow_messages) now instead.

It might also be worthwhile to create a Discord server focused on Rust WoW server emulation and link it from the awesome repo, I at least have benefitted significantly from asking questions on the [Ember 1.12 server discord](https://github.com/EmberEmu/Ember).

**Comment by arlyon** [comment]
Agreed. Let me do that.

**Comment by arlyon** [comment]
Server up! Have a look here https://discord.gg/RjSytaEuuX

![image](https://user-images.githubusercontent.com/8715352/192101976-4936afcd-6ada-4a55-ae32-f5a2a52c7e07.png)

Also generated a little mascot as well :laughing:
