### ISSUE TITLE
Why is ClientCrypto a Copy struct?

### ISSUE THREAD

**Issue by workingjubilee** [gtker/wow_srp#4]
See:

https://github.com/gtker/wow_srp/blob/4caed6b4afa1010b2e931131040d2b3d35de288a/src/wrath_header/mod.rs#L181-L200

This struct is Copy even though it has code that tries to enforce invariants by only allowing access through `&mut` access? This is very easy to simply ignore and accidentally copy around, and `&mut` access to a copied ClientCrypto won't mutate the original.

**Comment by gtker** [comment]
This is absolutely a good point and probably just a result of me being a little too eager to add derives to everything.

What do you use `wow_srp` for? Will you be able to use the git revision with this change?

**Comment by MeFisto94** [comment]
The issue was actually reported on behalf of me, since I asked on discord because I couldn't judge if Copy on these structs was indeed a mistake or my usage error and how I could work around it!
I'm using `wow_srp` for my research/prototype client as posted on the wow-rust discord (everyone doing wow and rust, check it out 👍 ).

I'm not eagerly updating `wow_srp`, though, as the API has changed slightly and (that is the reason why I wasn't on the new API to begin with), iirc, I needed to pin my version of `wow_srp` to the revision that is used in `wow_messages` otherwise I get mismatched structs. So as a heads up, bump that version occassionally (and update the client/server examples to the new API)

**Comment by gtker** [comment]
Good to know. I have updated the `wow_srp` version in `wow_messages`.
